baseURL = "https://lanpa.github.io/"
locale = "en-us"
title = "Tzu-Wei Huang"
theme = "hugo-profile"

defaultContentLanguage = "zh-Hant"
defaultContentLanguageInSubdir = false

[languages]
  [languages.zh-Hant]
    label = "中文"
    weight = 1
  [languages.en]
    label = "English"
    weight = 2
    title = "Tzu-Wei Huang"

[params]
  enableSearch = true
  homeInfoParams = { Title = "Tzu-Wei Huang", Content = "CV, ML, open-source and cycling adventures." }
  ShowReadingTime = true
  ShowShareButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowTagCloud = true
  defaultTheme = "auto"
  # Comments system
  comments = true

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/lanpa"

[[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@twhuangtw"

  [[params.socialIcons]]
    name = "strava"
    url = "https://strava.app.link/ClW1BqjVSVb"

[[params.socialIcons]]
  name = "rss"
  url = "/index.xml"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
[[menu.main]]
  name = "Academic"
  url = "/academic/"
  weight = 1

[[menu.main]]
  name = "Explorations"
  url = "/explorations/"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/work/"
  weight = 3

[[menu.main]]
  name = "DIY & Fix"
  url = "/fixing/"
  weight = 4

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 5

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 6

[services]
  [services.googleAnalytics]
    id = "G-WBXXLKTC4L"