baseURL = "https://lanpa.github.io/"
languageCode = "en-us"
title = "Tzu-Wei Huang"
theme = "PaperMod"

[params]
  homeInfoParams = { Title = "Tzu-Wei Huang", Content = "Ph.D. student and lecturer at NTHU, interested in machine learning." }
  ShowReadingTime = true
  ShowShareButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowTagCloud = true
  defaultTheme = "auto"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/lanpa"

[[params.socialIcons]]
  name = "rss"
  url = "/index.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
[[menu.main]]
  name = "Academic"
  url = "/academic/"
  weight = 1

[[menu.main]]
  name = "Explorations"
  url = "/explorations/"
  weight = 2

[[menu.main]]
  name = "Work & Projects"
  url = "/work/"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 5

