baseURL = "https://lanpa.github.io/"
languageCode = "en-us"
title = "Tzu-Wei Huang"
theme = "hugo-profile"

[params]
  enableSearch = true
  homeInfoParams = { Title = "Tzu-Wei Huang", Content = "Ph.D. student and lecturer at NTHU, interested in machine learning." }
  ShowReadingTime = true
  ShowShareButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowTagCloud = true
  defaultTheme = "auto"
  # Comments system
  comments = true

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/lanpa"

[[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@twhuangtw"

[[params.socialIcons]]
  name = "rss"
  url = "/index.xml"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
[[menu.main]]
  name = "Academic"
  url = "/academic/"
  weight = 1

[[menu.main]]
  name = "Explorations"
  url = "/explorations/"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/work/"
  weight = 3

[[menu.main]]
  name = "環騎台北"
  url = "/velodash/"
  weight = 4

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 5

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 6

[[menu.main]]
  name = "Fixing"
  url = "/fixing/"
  weight = 7

[services]
  [services.googleAnalytics]
    id = "G-WBXXLKTC4L"